function cfg = R25()
    % R25 FSAE car configuration (GENERATED from the design spec sheet)
    %
    % Auto-generated by scripts/generate_vehicle.py from the FSAE EV
    % Design Spec Sheet CSV. Fields annotated with their provenance:
    %   [CSV rN: ...]            -> direct mapping (value taken from CSV)
    %   TODO derivable (...)     -> derivable but ambiguous; left at default
    %   [not in spec sheet]      -> no CSV source; baseline default kept
    %
    % Units: SI throughout (m, kg, N, s, rad, Pa).

    cfg = VehicleConfig();

    cfg.name = "R25";
    %% ====================================================================
    %  VEHICLE-LEVEL CONSTANTS
    %  Mass includes the driver. x forward, y left, z up; CG height from
    %  the ground. Pitch/roll inertia are derived in SimpleChassis from
    %  mass + geometry; only yaw inertia is specified here.
    %  ====================================================================
    cfg.totalMass                    = 264;        %  [CSV r10: 196 kg + 68.0 kg driver] (kg, with driver)
    cfg.wheelbase                    = 1.528;      %  [CSV r8: 1528 mm] [m]
    cfg.trackWidth                   = 1.21;       %  [CSV r8: Front Track 1210 mm] [m]
    cfg.cgHeight                     = 0.256;        %  [CSV r9: 256 (unit column says 'mm' but value is clearly metres; kept as 256 m per baseline/R26)] [m]
    cfg.yawInertia                   = 130;        %  [not in spec sheet -- baseline default 130] [kg*m^2]
    cfg.airDensity                   = 1.225;      % [kg/m^3] (ISA standard; CSV aero r131 was evaluated at rho=1.162)
    cfg.staticFrontWeight            = 0.5095;     %  [CSV r11: 50.95% front] [0-1]
    cfg.brakeBiasFront               = 0.6;        %  TODO derivable: CSV r46: line pressures F 14.524/R 20.836 bar, r44 pistons F4/R2 => front clamp-fraction ~ 0.582 (rough; ignores piston bore 25 vs 25.4 mm). Verify against bias bar. [0-1]
    cfg.brakeForceCoefficient        = 0.7;        %  TODO derivable: CSV r46 is a 'Force @ 1g Deceleration' table; the system is sized for ~1g but brakeForceCoefficient is tyre-limited capacity. baseline 0.70 left as-is.
    cfg.maxSpeed                     = 80;         %  [not in spec sheet -- baseline default 80] [m/s] (~288 km/h)
    cfg.unsprungMass                 = 9.3;         %  TODO derivable: CSV r47-53 list upright/hub/bearing/axle/brake components as text (no clean per-corner mass). Sum them manually if needed; baseline 25 kg/corner left as-is. [kg/corner]

    %% ====================================================================
    %  AERODYNAMICS
    %  Whole-car aero is represented by one resultant at the center of
    %  pressure. xPosition > 0 is forward of CG, < 0 is behind. zPosition is
    %  kept at CG height so drag adds no artificial pitch moment.
    %  ====================================================================
    % NOTE: the spec sheet (r131-132) gives WHOLE-CAR aero, measured at
    % 80 kph. CSV whole-car totals:
    %   Downforce 1389.9 N  Drag 518.8 N  %Front 47.73
    %   Cl x RefArea(1.094 m^2) => ClA ~ 4.84  CdA ~ 1.81
    %   (downforce independently implies ClA ~ 4.84 -- ~-0% above Cl*Area; CSV is internally inconsistent)
    % xPosition = wheelbase * (%Front - staticFrontWeight).
    cfg.aero = struct( ...
        'xPosition', -0.049202, ...      % [CSV r131: 47.73% front CoP]
        'zPosition', cfg.cgHeight, ...   % Kept at CG height
        'ClA', 4.84, ...                 % [CSV r132: Cl * RefArea]
        'CdA', 1.81, ...                 % [CSV r132: Cd * RefArea]
        'pitchSensitivityClA', 0.0);     % [not in spec sheet]

    %% ====================================================================
    %  SUSPENSION
    %  Per-axle spring/damper. Wheel rate = springRate * motionRatio^2.
    %  ====================================================================

    cfg.suspension.front = struct( ...
        'springRate', 5250, ...         %   [CSV r21: 5.25 N/mm wheel rate (x1000; =springRate when motionRatio=1, else divide by MR^2)] [N/m]
        'dampingCoeff', 3000, ...        %   TODO derivable: CSV r24/r25: 400% critical damping (multi-speed curve; front). Single-value estimate C = 4.00*2*sqrt(k*m_sprung) = 3712 N*s/m (uses guessed unsprungMass 25 kg/corner). Same % shown for rebound (r25) -- likely a data-entry repeat. [N*s/m]
        'reboundCoeff', 4500);           % [N*s/m]  (see damping TODO above)

    cfg.suspension.rear = struct( ...
        'springRate', 5250, ...         %   [CSV r21: 5.25 N/mm wheel rate (x1000)] [N/m]
        'dampingCoeff', 2800, ...        % [N*s/m]  (see damping TODO above)
        'reboundCoeff', 4200);           % [N*s/m]

    cfg.suspension.motionRatio    = 1;     %   [CSV r26]
    cfg.suspension.bumpStopLength = 0.025;    %   TODO derivable: CSV r20: jounce travel F 25.4 mm / R 25.4 mm -> bumpStopLength ~ 0.025 m (front). Verify against installed stop.
    cfg.suspension.bumpStopRate   = 200000;   % [not in spec sheet] [N/m]
    cfg.suspension.tireSpringRate = 200000;   % [not in spec sheet] [N/m]

    % Suspension geometry: per-axle lookup tables indexed by wheel travel [m].
    cfg.suspension.geometry.front = struct( ...
        'travelGrid',       [-0.05 0 0.05], ...
        'camberCurve',      [0.5 0 -1.5] * pi / 180, ...   %   TODO derivable: CSV r27: ride camber F 49.9/R 66.8 deg/m; r30: static camber F -0.7/R ... deg. Build the 3-pt curve: middle = static camber, slope from ride camber (mind the sign convention: + = top-outward).
        'toeCurve',         [-0.05 0 0.05] * pi / 180, ... %   [not in spec sheet -- baseline default baseline]
        'motionRatioCurve', [0.93 0.95 0.97], ...
        'rollCenterHeight', 0.034977);                        %   [CSV r33: 34.977 mm]
    cfg.suspension.geometry.rear = struct( ...
        'travelGrid',       [-0.05 0 0.05], ...
        'camberCurve',      [0.25 0 -0.8] * pi / 180, ...
        'toeCurve',         [0.05 0 -0.05] * pi / 180, ...
        'motionRatioCurve', [0.94 0.95 0.96], ...
        'rollCenterHeight', 0.050496);                        %   [CSV r33: 50.496 mm]
    cfg.suspension.geometry.steering = struct( ...
        'steeringRatio',      1, ...
        'ackermann',          1.0207, ...
        'maxWheelSteerAngle', 0.6, ...                      % [not in spec sheet] [rad] (~34 deg)
        'rearSteerRatio',     0.0);

    % Anti-roll bars (baseline -- roll-rate TODO above).
    cfg.suspension.frontArb = struct( ...
        'stiffness', 1800, ...           % [N/m] at bar end
        'motionRatio', 0.95, ...         % [not in spec sheet]
        'leverArm', 0.26, ...            % [not in spec sheet] [m]
        'enabled', true);
    cfg.suspension.rearArb = struct( ...
        'stiffness', 1100, ...           % [N/m] at bar end
        'motionRatio', 0.95, ...
        'leverArm', 0.26, ...
        'enabled', true);

    cfg.suspension.rollStiffnessOverride = NaN;             % [not in spec sheet] derive from springs+ARBs
    cfg.suspension.coupleChassisRollToLoadTransfer = false; % [not in spec sheet]

    %% ====================================================================
    %  CHASSIS (sprung-mass platform heave/pitch/roll)
    %  ====================================================================
    cfg.chassis = struct( ...
        'heaveStiffness', 160000, ...    % [not in spec sheet] [N/m]
        'heaveDamping', 12000, ...       % [not in spec sheet] [N*s/m]
        'pitchStiffness', 90000, ...     % [not in spec sheet] [N*m/rad]
        'pitchDamping', 6000, ...        % [not in spec sheet]
        'rollStiffness', 55000, ...      %   TODO derivable: CSV r22: roll rate F 671.26/R 671.26 N*m/deg (chassis-to-wheel). Per-element ARB.stiffness and chassis.rollStiffness must be derived via geometry/MR; left at baseline. [N*m/rad]
        'rollDamping', 5000, ...         % [not in spec sheet] [N*m*s/rad]
        'torsionalRigidity', 178307, ... %   [CSV r78: 3112.04 N*m/deg (Physical Test) x 180/pi] [N*m/rad]
        'torsionalDamping', 2000);       % [not in spec sheet] [N*m*s/rad]

    %% ====================================================================
    %  POWERTRAIN
    %  Single-speed EV. matFile = '' selects the default motor map;
    %  final drive is fixed in the map. Drivetrain is RWD.
    %    differential.type: 'open' | 'locked' (spool) | 'lsd'
    %  ====================================================================
    % matFile '' = default EMRAX 228 map (CSV r85 confirms 'Emrax 228')
    cfg.powertrain = struct( ...
        'matFile', '', ...
        'efficiency', 0.85, ...          % [not in spec sheet] [0-1]
        'differential', struct('type', 'lsd'));  %   [CSV r122: Drexler M-Diff LSD, non-adjustable preload]
    % TODO lsd params: VehicleManager.def supplies preload/ramp/
    % speedGain/biasRatio defaults if omitted; set explicitly if known.

    %% ====================================================================
    %  TIRE
    %  Pacejka Magic Formula (MF 6.1) via MFeval; tirFile lives in +Tire/.
    %  ====================================================================
    % NOTE: CSV r14 lists '16.0x7.5-10 R20 Hoosier'. The default tirFile below is for an
    % 18x7.5-10 Hoosier; if the size differs, supply the matching
    % .tir file and update wheelRadius accordingly.
    cfg.tire = struct( ...
        'tirFile', '43105_18x7.5_10_R25B_7.tir', ... % [verify vs CSV r14 tire size]
        'wheelInertia', 0.5, ...         % [not in spec sheet] [kg*m^2]
        'relaxationLength', 0.30, ...    % [not in spec sheet] [m]
        'wheelRadius', 0.241935, ...     % TODO: CSV r14 size -> derive rolling radius
        'rollingResistanceCoeff', 0.015, ... % [not in spec sheet]
        'bearingDragCoeff', 0);          % [not in spec sheet]
end
