function tests = CorrelationReplayTest
tests = functiontests(localfunctions);
end

function testReplayProfileIntegratesDistanceFromSpeed(testCase)
profile = lts.correlation.CorrelationReplayProfile( ...
    'Time', [10; 11; 12], ...
    'Throttle', [0; 1; 0], ...
    'Brake', [0; 0; 0.5], ...
    'Steer', [0; 0.2; 0.4], ...
    'Speed', [10; 10; 10]);

verifyEqual(testCase, profile.time, [0; 1; 2], 'AbsTol', 1e-12);
verifyEqual(testCase, profile.distance, [0; 10; 20], 'AbsTol', 1e-12);
end

function testReplayProfileSamplesByDistance(testCase)
profile = lts.correlation.CorrelationReplayProfile( ...
    'Time', [0; 1; 2], ...
    'Distance', [0; 10; 20], ...
    'Throttle', [0; 1; 0], ...
    'Brake', [0; 0; 0.5], ...
    'BrakePressureFrontBar', [0; 6; 10], ...
    'BrakePressureRearBar', [0; 3; 5], ...
    'Steer', [0; 0.2; 0.4], ...
    'Speed', [10; 20; 10]);

input = profile.sampleByDistance(5);

verifyEqual(testCase, input.throttle, 0.5, 'AbsTol', 1e-12);
verifyEqual(testCase, input.brake, 0, 'AbsTol', 1e-12);
verifyEqual(testCase, input.brakePressureFrontBar, 3, 'AbsTol', 1e-12);
verifyEqual(testCase, input.brakePressureRearBar, 1.5, 'AbsTol', 1e-12);
verifyEqual(testCase, input.steer, 0.1, 'AbsTol', 1e-12);
verifyEqual(testCase, input.targetSpeed, 15, 'AbsTol', 1e-12);
end

function testReplayProfileReadsOptionalCorrelationColumns(testCase)
fileName = [tempname '.csv'];
cleanup = onCleanup(@() deleteIfExists(fileName)); %#ok<NASGU>
T = table( ...
    [0; 1], [0; 10], [0.1; 0.2], [0; 0.3], [4; 8], [2; 6], ...
    [0.01; 0.02], [8; 9], ...
    [8.1; 8.2], [8.3; 8.4], [NaN; NaN], [8.5; 8.6], ...
    [7.5; 8.5], [0.4; 0.5], [0.05; 0.06], ...
    [1.0; 1.1], [2.0; 2.1], [0.3; 0.4], ...
    [0.55; 0.65], [0.7; 0.8], [0.5; 0.6], ...
    [-0.05; -0.15], [-0.2; -0.3], [-0.1; -0.2], ...
    'VariableNames', {'time_s', 'distance_m', 'throttle_ratio', ...
    'brake_ratio', 'brake_pressure_front_bar', 'brake_pressure_rear_bar', ...
    'steer_rad', 'speed_mps', 'wheel_speed_fl_mps', 'wheel_speed_fr_mps', ...
    'wheel_speed_rl_mps', 'wheel_speed_rr_mps', 'vx_mps', 'vy_mps', 'body_slip_rad', ...
    'gps_lat_deg', 'gps_lon_deg', 'gps_course_rad', 'front_lat_accel_g', ...
    'rear_lat_accel_g', 'lat_accel_g', 'front_long_accel_g', ...
    'rear_long_accel_g', 'long_accel_g'});
writetable(T, fileName);

profile = lts.correlation.CorrelationReplayProfile.fromCsv(fileName);

verifyTrue(testCase, profile.hasVelocity());
verifyTrue(testCase, profile.hasBodySlip());
verifyTrue(testCase, profile.hasBrakePressure());
verifyTrue(testCase, profile.hasGpsCourse());
verifyTrue(testCase, profile.hasLatAccel());
verifyTrue(testCase, profile.hasInitialWheelSpeeds());
verifyEqual(testCase, profile.brakePressureFrontBar, [4; 8], 'AbsTol', 1e-12);
verifyEqual(testCase, profile.brakePressureRearBar, [2; 6], 'AbsTol', 1e-12);
verifyEqual(testCase, profile.wheelSpeedFL, [8.1; 8.2], 'AbsTol', 1e-12);
verifyEqual(testCase, profile.wheelSpeedFR, [8.3; 8.4], 'AbsTol', 1e-12);
verifyTrue(testCase, all(isnan(profile.wheelSpeedRL)));
verifyEqual(testCase, profile.wheelSpeedRR, [8.5; 8.6], 'AbsTol', 1e-12);
verifyEqual(testCase, profile.vx, [7.5; 8.5], 'AbsTol', 1e-12);
verifyEqual(testCase, profile.vy, [0.4; 0.5], 'AbsTol', 1e-12);
verifyEqual(testCase, profile.bodySlip, [0.05; 0.06], 'AbsTol', 1e-12);
verifyEqual(testCase, profile.gpsCourse, [0.3; 0.4], 'AbsTol', 1e-12);
verifyEqual(testCase, profile.frontLatAccelG, [0.55; 0.65], 'AbsTol', 1e-12);
verifyEqual(testCase, profile.rearLatAccelG, [0.7; 0.8], 'AbsTol', 1e-12);
verifyEqual(testCase, profile.latAccelG, [0.5; 0.6], 'AbsTol', 1e-12);
verifyEqual(testCase, profile.frontLongAccelG, [-0.05; -0.15], 'AbsTol', 1e-12);
verifyEqual(testCase, profile.rearLongAccelG, [-0.2; -0.3], 'AbsTol', 1e-12);
verifyEqual(testCase, profile.longAccelG, [-0.1; -0.2], 'AbsTol', 1e-12);
end

function testTrackAlignmentEstimatesKnownStationFromCourse(testCase)
track = localCircleTrack(50, 120);
knownStation = 80;
distance = (0:5:100).';
[trackS, trackHeading, trackLength] = ...
    lts.correlation.CorrelationTrackAlignment.trackHeadingSamples(track);
course = lts.correlation.CorrelationTrackAlignment.headingAtStation( ...
    trackS, trackHeading, trackLength, knownStation + distance);
profile = localProfileWithCourse(distance, course);

[station, errorDeg, sampleCount] = ...
    lts.correlation.CorrelationTrackAlignment.estimateStartStationFromCourse(track, profile, 100, 0.5);

verifyEqual(testCase, station, knownStation, 'AbsTol', 0.51);
verifyLessThan(testCase, errorDeg, 0.1);
verifyEqual(testCase, sampleCount, numel(distance));
end

function testTrackRebasePreservesLengthAndMovesStart(testCase)
track = localCircleTrack(50, 120);
startStation = 80;
expectedStart = localTrackPointAtStation(track, startStation);

rebased = lts.correlation.CorrelationTrackAlignment.rebaseTrack(track, startStation);
points = rebased.getTrackPoints();

verifyEqual(testCase, rebased.getTotalLength(), track.getTotalLength(), 'AbsTol', 1e-9);
verifyEqual(testCase, points(1, :), expectedStart, 'AbsTol', 1e-10);
verifyTrue(testCase, rebased.Closed);
end

function testTrackAlignmentReportsLargeHeadingMismatch(testCase)
track = localCircleTrack(50, 120);
heading = track.getHeading();
profile = localProfileWithCourse([0; 1; 2], repmat(heading(1) + pi, 3, 1));

errorDeg = lts.correlation.CorrelationTrackAlignment.initialHeadingErrorDeg(track, profile);

verifyEqual(testCase, errorDeg, 180, 'AbsTol', 1e-9);
end

function testStateInitializerCanIgnoreLoggedYawRate(testCase)
track = localCircleTrack(50, 120);
profile = lts.correlation.CorrelationReplayProfile( ...
    'Time', [0; 1], ...
    'Distance', [0; 10], ...
    'Throttle', [0; 0], ...
    'Brake', [0; 0], ...
    'Steer', [0; 0], ...
    'Speed', [5; 5], ...
    'YawRate', [2; 2]);

stateWithoutYawRate = lts.correlation.CorrelationStateInitializer.fromReplayProfile( ...
    profile, track, [], 'UseLoggedYawRate', false);
stateWithYawRate = lts.correlation.CorrelationStateInitializer.fromReplayProfile( ...
    profile, track, [], 'UseLoggedYawRate', true);

verifyEqual(testCase, stateWithoutYawRate.yawRate, 0, 'AbsTol', 1e-12);
verifyEqual(testCase, stateWithYawRate.yawRate, 2, 'AbsTol', 1e-12);
end

function testStateInitializerSeedsSideslipFromLoggedYawRate(testCase)
vehicle = lts.vehicle.VehicleManager([], [], [], [], []);
vehicle.wheelbase = 1.6;
vehicle.staticFrontWeight = 0.5;
profile = lts.correlation.CorrelationReplayProfile( ...
    'Time', [0; 1], ...
    'Distance', [0; 10], ...
    'Throttle', [0; 0], ...
    'Brake', [0; 0], ...
    'Steer', [0; 0], ...
    'Speed', [10; 10], ...
    'YawRate', [1; 1]);

stateWithYawRate = lts.correlation.CorrelationStateInitializer.fromReplayProfile( ...
    profile, [], vehicle, 'UseLoggedYawRate', true);
stateWithoutYawRate = lts.correlation.CorrelationStateInitializer.fromReplayProfile( ...
    profile, [], vehicle, 'UseLoggedYawRate', false);

expectedVy = 0.8;
expectedVx = sqrt(10^2 - expectedVy^2);
verifyEqual(testCase, stateWithYawRate.vx, expectedVx, 'AbsTol', 1e-12);
verifyEqual(testCase, stateWithYawRate.vy, expectedVy, 'AbsTol', 1e-12);
verifyEqual(testCase, stateWithYawRate.speed, 10, 'AbsTol', 1e-12);
verifyEqual(testCase, stateWithoutYawRate.vx, 10, 'AbsTol', 1e-12);
verifyEqual(testCase, stateWithoutYawRate.vy, 0, 'AbsTol', 1e-12);
end

function testStateInitializerIgnoresGpsCourseAndTrackHeading(testCase)
track = localCircleTrack(50, 120);
profile = lts.correlation.CorrelationReplayProfile( ...
    'Time', [0; 1], ...
    'Distance', [0; 10], ...
    'Throttle', [0; 0], ...
    'Brake', [0; 0], ...
    'Steer', [0; 0], ...
    'Speed', [5; 5], ...
    'GpsCourse', [pi / 2; pi / 2]);

state = lts.correlation.CorrelationStateInitializer.fromReplayProfile(profile, track, []);

verifyEqual(testCase, state.x, 0, 'AbsTol', 1e-12);
verifyEqual(testCase, state.y, 0, 'AbsTol', 1e-12);
verifyEqual(testCase, state.yaw, 0, 'AbsTol', 1e-12);
verifyEqual(testCase, state.vx, 5, 'AbsTol', 1e-12);
verifyEqual(testCase, state.vy, 0, 'AbsTol', 1e-12);
end

function testStateInitializerUsesBodyVelocityBeforeBodySlip(testCase)
profile = lts.correlation.CorrelationReplayProfile( ...
    'Time', [0; 1], ...
    'Distance', [0; 10], ...
    'Throttle', [0; 0], ...
    'Brake', [0; 0], ...
    'Steer', [0; 0], ...
    'Speed', [20; 20], ...
    'Vx', [8; 8], ...
    'Vy', [6; 6], ...
    'BodySlip', [0.4; 0.4]);

state = lts.correlation.CorrelationStateInitializer.fromReplayProfile(profile, [], []);

verifyEqual(testCase, state.vx, 8, 'AbsTol', 1e-12);
verifyEqual(testCase, state.vy, 6, 'AbsTol', 1e-12);
verifyEqual(testCase, state.speed, 10, 'AbsTol', 1e-12);
verifyEqual(testCase, state.bodySlipAngle, atan2(6, 8), 'AbsTol', 1e-12);
end

function testStateInitializerUsesBodySlipWhenVelocityMissing(testCase)
beta = 0.2;
profile = lts.correlation.CorrelationReplayProfile( ...
    'Time', [0; 1], ...
    'Distance', [0; 10], ...
    'Throttle', [0; 0], ...
    'Brake', [0; 0], ...
    'Steer', [0; 0], ...
    'Speed', [10; 10], ...
    'BodySlip', [beta; beta]);

state = lts.correlation.CorrelationStateInitializer.fromReplayProfile(profile, [], []);

verifyEqual(testCase, state.vx, 10 * cos(beta), 'AbsTol', 1e-12);
verifyEqual(testCase, state.vy, 10 * sin(beta), 'AbsTol', 1e-12);
verifyEqual(testCase, state.speed, 10, 'AbsTol', 1e-12);
end

function testStateInitializerSeedsLoggedWheelSpeedsWithMissingCornerFallback(testCase)
track = lts.components.TestTrack('straight10');
vehicle = lts.vehicle.VehicleManager.fromConfig(lts.vehicles.R25(), track, 0.001);
profile = lts.correlation.CorrelationReplayProfile( ...
    'Time', [0; 1], ...
    'Distance', [0; 10], ...
    'Throttle', [0; 0], ...
    'Brake', [0; 0], ...
    'Steer', [0; 0], ...
    'Speed', [9; 9], ...
    'WheelSpeedFL', [8; 8], ...
    'WheelSpeedFR', [10; 10], ...
    'WheelSpeedRL', [NaN; NaN], ...
    'WheelSpeedRR', [12; 12]);

state = lts.correlation.CorrelationStateInitializer.fromReplayProfile(profile, track, vehicle);

verifyEqual(testCase, vehicle.tire.FL.angularVelocity, ...
    8 / vehicle.tire.FL.wheelRadius, 'AbsTol', 1e-12);
verifyEqual(testCase, vehicle.tire.FR.angularVelocity, ...
    10 / vehicle.tire.FR.wheelRadius, 'AbsTol', 1e-12);
verifyEqual(testCase, vehicle.tire.RL.angularVelocity, ...
    10 / vehicle.tire.RL.wheelRadius, 'AbsTol', 1e-12);
verifyEqual(testCase, vehicle.tire.RR.angularVelocity, ...
    12 / vehicle.tire.RR.wheelRadius, 'AbsTol', 1e-12);
end

function testReplayDriverSamplesByTime(testCase)
profile = lts.correlation.CorrelationReplayProfile( ...
    'Time', [0; 1; 2], ...
    'Distance', [0; 10; 20], ...
    'Throttle', [0; 1; 0], ...
    'Brake', [0; 0; 0.5], ...
    'Steer', [0; 0.2; 0.4], ...
    'Speed', [10; 20; 10]);
driver = lts.correlation.TelemetryReplayDriver(profile, 'ReplayDomain', 'time');
state = lts.simulation.VehicleState('time', 0.5, 'speed', 10);

input = driver.computeInput(state, struct('s', 0));

verifyEqual(testCase, input.throttle, 0.5, 'AbsTol', 1e-12);
verifyEqual(testCase, input.steer, 0.1, 'AbsTol', 1e-12);
end

function testSimulatorReplayInputPolicyAllowsMeasuredOverlap(testCase)
simulator = lts.simulation.Simulator(lts.vehicle.VehicleManager([], [], [], [], []), [], 0.1);
simulator.enforcePedalExclusivity = false;
simulator.applySteeringSlew = false;
state = lts.simulation.VehicleState('steer', 0);
input = struct('throttle', 0.7, 'brake', 0.2, 'steer', 0.5);

normalized = simulator.normalizeDriverInput(input, state);

verifyEqual(testCase, normalized.throttle, 0.7, 'AbsTol', 1e-12);
verifyEqual(testCase, normalized.brake, 0.2, 'AbsTol', 1e-12);
verifyEqual(testCase, normalized.steer, 0.5, 'AbsTol', 1e-12);
end

function testSimulatorDefaultInputPolicyKeepsLegacyExclusivity(testCase)
simulator = lts.simulation.Simulator(lts.vehicle.VehicleManager([], [], [], [], []), [], 0.1);
state = lts.simulation.VehicleState('steer', 0);
input = struct('throttle', 0.7, 'brake', 0.2, 'steer', 0.5);

normalized = simulator.normalizeDriverInput(input, state);

verifyEqual(testCase, normalized.throttle, 0, 'AbsTol', 1e-12);
verifyEqual(testCase, normalized.brake, 0.2, 'AbsTol', 1e-12);
end

function testReplayPolicyCanDisableOffTrackStop(testCase)
simulator = lts.simulation.Simulator(lts.vehicle.VehicleManager([], [], [], [], []), [], 0.1);

verifyTrue(testCase, simulator.stopOnOffTrack);
verifyTrue(testCase, simulator.stopAtTrackEnd);
verifyTrue(testCase, isinf(simulator.stopTime));
simulator.restoreReplayPolicies([], [], true, true, "pressure", false, false, 12.5);

verifyFalse(testCase, simulator.stopOnOffTrack);
verifyFalse(testCase, simulator.stopAtTrackEnd);
verifyEqual(testCase, simulator.stopTime, 12.5, 'AbsTol', 1e-12);
verifyEqual(testCase, simulator.brakeMode, "pressure");
end

function testRunCorrelationAppliesVehicleTuningFile(testCase)
replayFile = [tempname '.csv'];
outputBase = tempname;
cleanup = onCleanup(@() cleanupCorrelationFiles(replayFile, outputBase)); %#ok<NASGU>
T = table( ...
    [0; 0.01; 0.02], [0; 0.02; 0.04], [0; 0; 0], [0; 0; 0], ...
    [0; 0; 0], [2; 2; 2], ...
    'VariableNames', {'time_s', 'distance_m', 'throttle_ratio', ...
    'brake_ratio', 'steer_rad', 'speed_mps'});
writetable(T, replayFile);

[stateLog, ~, outputs] = lts.app.run_correlation( ...
    'ReplayCsv', replayFile, ...
    'VehicleConfig', @lts.vehicles.R25, ...
    'TuningFile', 'R25_correlation_tuning', ...
    'Track', 'straight10', ...
    'Dt', 0.01, ...
    'OutputBase', outputBase, ...
    'ExportMoTeC', false, ...
    'UseLoggedPosition', false, ...
    'UseLoggedYawRate', false);

verifyEqual(testCase, outputs.vehicleConfig, 'R25_corrTune');
verifyGreaterThan(testCase, numel(stateLog.time), 0);
verifyEqual(testCase, unique(stateLog.brakePressureMode), false);
end

function testReplayContinuesOffTrackToReplayEnd(testCase)
dt = 0.01;
track = localCircleTrack(20, 40);
track.Width = 2;
profile = lts.correlation.CorrelationReplayProfile( ...
    'Time', (0:dt:0.05).', ...
    'Distance', (0:dt:0.05).' * 2, ...
    'Throttle', linspace(0.2, 0.7, 6).', ...
    'Brake', zeros(6, 1), ...
    'Steer', zeros(6, 1), ...
    'Speed', 2 * ones(6, 1), ...
    'LatAccelG', linspace(0.1, 0.6, 6).', ...
    'FrontLatAccelG', linspace(0.2, 0.7, 6).', ...
    'RearLatAccelG', linspace(-0.1, 0.4, 6).', ...
    'LongAccelG', linspace(-0.2, 0.3, 6).', ...
    'FrontLongAccelG', linspace(-0.3, 0.2, 6).', ...
    'RearLongAccelG', linspace(-0.4, 0.1, 6).', ...
    'YawRate', linspace(1.0, 1.5, 6).');
vehicle = lts.vehicle.VehicleManager.fromConfig(lts.vehicles.R25(), track, dt);
simulator = lts.simulation.Simulator(vehicle, [], dt);
initialState = lts.simulation.VehicleState( ...
    'x', 100, ...
    'y', 100, ...
    'yaw', 0, ...
    'speed', 2, ...
    'vx', 2);

[stateLog, lapTime] = simulator.simulateReplay( ...
    initialState, track, profile, ...
    'ReplayDomain', 'time', ...
    'StopOnOffTrack', false, ...
    'StopAtTrackEnd', false, ...
    'StopAtReplayEnd', true);

verifyGreaterThanOrEqual(testCase, lapTime, 0.04);
verifyTrue(testCase, any(~stateLog.onTrack));
verifyLessThan(testCase, min(stateLog.trackLimitMargin), 0);
verifyEqual(testCase, stateLog.controlTime, (0:dt:0.04)', 'AbsTol', 1e-12);
verifyEqual(testCase, stateLog.controlS, (0:dt:0.04)' * 2, 'AbsTol', 1e-12);
verifyEqual(testCase, stateLog.replayThrottle, linspace(0.2, 0.6, 5)', 'AbsTol', 1e-12);
verifyEqual(testCase, stateLog.replayBrake, zeros(5, 1), 'AbsTol', 1e-12);
verifyEqual(testCase, stateLog.replaySpeed, 2 * ones(5, 1), 'AbsTol', 1e-12);
verifyEqual(testCase, stateLog.replayLatAccelG, linspace(0.1, 0.5, 5)', 'AbsTol', 1e-12);
verifyEqual(testCase, stateLog.replayFrontLatAccelG, linspace(0.2, 0.6, 5)', 'AbsTol', 1e-12);
verifyEqual(testCase, stateLog.replayRearLatAccelG, linspace(-0.1, 0.3, 5)', 'AbsTol', 1e-12);
verifyEqual(testCase, stateLog.replayLongAccelG, linspace(-0.2, 0.2, 5)', 'AbsTol', 1e-12);
verifyEqual(testCase, stateLog.replayFrontLongAccelG, linspace(-0.3, 0.1, 5)', 'AbsTol', 1e-12);
verifyEqual(testCase, stateLog.replayRearLongAccelG, linspace(-0.4, 0, 5)', 'AbsTol', 1e-12);
verifyEqual(testCase, stateLog.replayYawRate, linspace(1.0, 1.4, 5)', 'AbsTol', 1e-12);
end

function testFreeReplayDoesNotProjectToTrack(testCase)
dt = 0.01;
track = localCircleTrack(20, 40);
track.Width = 2;
profile = lts.correlation.CorrelationReplayProfile( ...
    'Time', (0:dt:0.05).', ...
    'Distance', (0:dt:0.05).' * 2, ...
    'Throttle', zeros(6, 1), ...
    'Brake', zeros(6, 1), ...
    'Steer', zeros(6, 1), ...
    'Speed', 2 * ones(6, 1));
vehicle = lts.vehicle.VehicleManager.fromConfig(lts.vehicles.R25(), track, dt);
simulator = lts.simulation.Simulator(vehicle, [], dt);
initialState = lts.simulation.VehicleState( ...
    'x', 100, ...
    'y', 100, ...
    'yaw', 0, ...
    'speed', 2, ...
    'vx', 2);

[stateLog, lapTime] = simulator.simulateReplay( ...
    initialState, track, profile, ...
    'ReplayDomain', 'time', ...
    'ReferenceMode', 'free', ...
    'SurfaceMu', 1.2, ...
    'StopAtReplayEnd', true);

verifyGreaterThanOrEqual(testCase, lapTime, 0.04);
verifyTrue(testCase, all(stateLog.onTrack));
verifyEqual(testCase, stateLog.trackLimitMargin, zeros(size(stateLog.trackLimitMargin)), ...
    'AbsTol', 1e-12);
verifyLessThan(testCase, max(stateLog.s), 1);
verifyEqual(testCase, stateLog.lateralError, zeros(size(stateLog.lateralError)), ...
    'AbsTol', 1e-12);
end

function track = localCircleTrack(radius, nPoints)
theta = linspace(0, 2*pi, nPoints + 1).';
theta(end) = [];
points = radius * [cos(theta), sin(theta)];
track = lts.components.WaypointTrack(points, ...
    'Width', 5, ...
    'Closed', true, ...
    'Name', 'CorrelationTestCircle');
end

function profile = localProfileWithCourse(distance, course)
n = numel(distance);
profile = lts.correlation.CorrelationReplayProfile( ...
    'Time', (0:n-1).', ...
    'Distance', distance(:), ...
    'Throttle', zeros(n, 1), ...
    'Brake', zeros(n, 1), ...
    'Steer', zeros(n, 1), ...
    'Speed', ones(n, 1), ...
    'GpsCourse', course(:));
end

function point = localTrackPointAtStation(track, station)
points = track.getTrackPoints();
s = lts.components.Track.cumulativeArcLength(points, true);
p = [points; points(1, :)];
station = mod(station, s(end));
point = [ ...
    interp1(s, p(:, 1), station, 'linear'), ...
    interp1(s, p(:, 2), station, 'linear')];
end

function deleteIfExists(fileName)
if exist(fileName, 'file')
    delete(fileName);
end
end

function cleanupCorrelationFiles(replayFile, outputBase)
deleteIfExists(replayFile);
deleteIfExists([outputBase '.csv']);
deleteIfExists([outputBase '.ld']);
end
