function tests = CorrelationSegmentsTest
tests = functiontests(localfunctions);
end

function testSegmentRunnerRequiresReplayCsv(testCase)
verifyError(testCase, ...
    @() lts.app.run_correlation_segments('ReplayCsv', ''), ...
    'run_correlation_segments:MissingInput');
end

function testSegmentRunnerSplitsSyntheticReplayIntoScoredSegments(testCase)
    assumeTrue(testCase, tireDataAvailable(), 'TTC tire data not present: see src/+lts/+components/+Tire/README.md');
replayCsv = [tempname '.csv'];
cleanup = onCleanup(@() deleteIfExists(replayCsv)); %#ok<NASGU>
writeSyntheticReplay(replayCsv, 0.01, 4.0);

[segments, pooled, outputs] = lts.app.run_correlation_segments( ...
    'ReplayCsv', replayCsv, ...
    'VehicleConfig', @lts.vehicles.R25, ...
    'Track', 'straight10', ...
    'PowertrainMode', 'motor_torque_command', ...
    'Dt', 0.01, ...
    'SegmentLengthS', 1.5, ...
    'SettleWindowS', 0.25, ...
    'ShowProgress', false);

verifyEqual(testCase, outputs.segmentCount, 2, 'AbsTol', 0);
verifyEqual(testCase, outputs.telemetryMode, 'lean');
verifyEqual(testCase, numel(segments), 2, 'AbsTol', 0);
verifyEqual(testCase, segments(1).t0, 0, 'AbsTol', 1e-9);
verifyEqual(testCase, segments(2).t0, 1.5, 'AbsTol', 1e-9);
verifyEqual(testCase, segments(2).t1, 3.0, 'AbsTol', 1e-9);
verifyTrue(testCase, all(strcmp({segments.status}, 'scored')));
verifyEqual(testCase, pooled.scoredSamples, ...
    sum([segments.scoredSamples]), 'AbsTol', 0);
verifyGreaterThan(testCase, pooled.scoredSamples, 0);
verifyFalse(testCase, isnan(pooled.speed_rmse_mps));
verifyFalse(testCase, isnan(pooled.yaw_rmse_radps));
verifyGreaterThan(testCase, pooled.speed_rmse_mps, 0);
end

function testSettleWindowExcludesBoundarySamples(testCase)
    assumeTrue(testCase, tireDataAvailable(), 'TTC tire data not present: see src/+lts/+components/+Tire/README.md');
replayCsv = [tempname '.csv'];
cleanup = onCleanup(@() deleteIfExists(replayCsv)); %#ok<NASGU>
writeSyntheticReplay(replayCsv, 0.01, 4.0);

[segments, ~, ~] = lts.app.run_correlation_segments( ...
    'ReplayCsv', replayCsv, ...
    'VehicleConfig', @lts.vehicles.R25, ...
    'Track', 'straight10', ...
    'PowertrainMode', 'motor_torque_command', ...
    'Dt', 0.01, ...
    'SegmentLengthS', 1.5, ...
    'SettleWindowS', 0.25, ...
    'ShowProgress', false);

% Scored window is [0.25, 1.5) s at dt=0.01 -> 125 samples, allow endpoint slack.
verifyGreaterThanOrEqual(testCase, segments(1).scoredSamples, 120);
verifyLessThanOrEqual(testCase, segments(1).scoredSamples, 130);
end

function testSegmentRangeShardsWithoutRerunningOthers(testCase)
    assumeTrue(testCase, tireDataAvailable(), 'TTC tire data not present: see src/+lts/+components/+Tire/README.md');
replayCsv = [tempname '.csv'];
cleanup = onCleanup(@() deleteIfExists(replayCsv)); %#ok<NASGU>
writeSyntheticReplay(replayCsv, 0.01, 4.0);

[segments, ~, outputs] = lts.app.run_correlation_segments( ...
    'ReplayCsv', replayCsv, ...
    'VehicleConfig', @lts.vehicles.R25, ...
    'Track', 'straight10', ...
    'PowertrainMode', 'motor_torque_command', ...
    'Dt', 0.01, ...
    'SegmentLengthS', 1.5, ...
    'SettleWindowS', 0.25, ...
    'SegmentRange', 2, ...
    'ShowProgress', false);

verifyEqual(testCase, outputs.segmentCount, 2, 'AbsTol', 0);
verifyEqual(testCase, numel(segments), 1, 'AbsTol', 0);
verifyEqual(testCase, segments(1).t0, 1.5, 'AbsTol', 1e-9);
end

function writeSyntheticReplay(replayCsv, dt, durationS)
% Gentle steer weave at constant speed: enough lateral activity to exercise
% the model, mild enough that free replay stays well behaved. The kinematic
% yaw and lateral channels are consistent with the steer command.
n = round(durationS / dt) + 1;
t = (0:n-1).' * dt;
steer = 0.04 * sin(2 * pi * t / 1.0);
yawRate = 10 * tan(steer) / 1.528;
latG = 10 * yawRate / 9.80665;
T = table(t, t * 10, zeros(n, 1), zeros(n, 1), ...
    -90 * ones(n, 1), 20 * ones(n, 1), steer, 10 * ones(n, 1), ...
    yawRate, latG, ...
    'VariableNames', {'time_s', 'distance_m', 'throttle_ratio', ...
    'brake_ratio', 'regen_torque_nm', 'motor_torque_command_nm', ...
    'steer_rad', 'speed_mps', 'yaw_rate_radps', 'lat_accel_g'});
writetable(T, replayCsv);
end

function deleteIfExists(fileName)
if exist(fileName, 'file')
    delete(fileName);
end
end
