function tests = GovernancePredictionTest
tests = functiontests(localfunctions);
end

function setupOnce(testCase)
root = lts.util.repoRoot(mfilename('fullpath'));
testCase.TestData.root = root;
testCase.TestData.manifestFile = fullfile(root, 'config', 'governance', ...
    'r25_parameter_manifest.json');
testCase.TestData.artifactFile = fullfile(root, 'config', 'governance', ...
    'r25_provisional_calibration.json');
end

function testManifestAndArtifactLoad(testCase)
manifest = lts.governance.ParameterManifest.load( ...
    testCase.TestData.manifestFile);
artifact = lts.governance.CalibrationArtifact.load( ...
    testCase.TestData.artifactFile, manifest);
verifyEqual(testCase, string(manifest.id), "r25-governed-v1");
verifyEqual(testCase, string(artifact.certification), "provisional");
verifyFalse(testCase, logical(artifact.legacy));
end

function testMeasuredAndDesignParametersCannotBeFitted(testCase)
manifest = lts.governance.ParameterManifest.load( ...
    testCase.TestData.manifestFile);
verifyError(testCase, @() ...
    lts.governance.ParameterManifest.assertCalibratable(manifest, "total_mass"), ...
    'lts_governance_ParameterManifest:FitForbidden');
verifyError(testCase, @() ...
    lts.governance.ParameterManifest.assertCalibratable(manifest, "wheelbase"), ...
    'lts_governance_ParameterManifest:FitForbidden');
end

function testLegacyTunerRequiresExplicitDiagnosticOptIn(testCase)
verifyError(testCase, @() lts.app.tune_correlation(), ...
    'tune_correlation:LegacyOptInRequired');
end

function testLegacyArtifactCannotBuildGovernedVehicle(testCase)
manifest = lts.governance.ParameterManifest.load( ...
    testCase.TestData.manifestFile);
artifact = lts.governance.CalibrationArtifact.load( ...
    testCase.TestData.artifactFile, manifest);
artifact.legacy = true;
verifyError(testCase, @() lts.governance.GovernedVehicle.build( ...
    @lts.vehicles.R25, manifest, artifact), ...
    'lts_governance_CalibrationArtifact:LegacyForbidden');
end

function testMassChangeUpdatesCoupledPropertiesWithoutRefit(testCase)
governed = localGoverned(testCase);
change = struct('schema', "lts.prediction.design-change.v1", ...
    'id', "remove_mass", 'source', "scale", ...
    'provenance', "weighed component and installed position", ...
    'operations', struct('type', "mass", 'deltaMassKg', -5, ...
        'xFromCgM', 0.2, 'yFromCgM', 0.1, 'zFromGroundM', 0.15));
variant = lts.prediction.DesignChange.apply(governed, change);
verifyEqual(testCase, variant.config.totalMass, ...
    governed.config.totalMass - 5, 'AbsTol', 1e-12);
verifyNotEqual(testCase, variant.config.cgHeight, governed.config.cgHeight);
verifyNotEqual(testCase, variant.config.yawInertia, governed.config.yawInertia);
verifyEqual(testCase, variant.calibrationId, governed.calibrationId);
verifyEqual(testCase, variant.artifact, governed.artifact);
end

function testIncompleteAeroChangeRejected(testCase)
change = struct('schema', "lts.prediction.design-change.v1", ...
    'id', "bad_aero", 'source', "CFD", 'provenance', "partial", ...
    'operations', struct('type', "aero_map", 'ClA', 5, 'CdA', 2));
verifyError(testCase, @() lts.prediction.DesignChange.validate(change), ...
    'lts_prediction_DesignChange:IncompleteOperation');
end

function testPairedUncertaintyIsSeededAndDoesNotMutateBaseline(testCase)
governed = localGoverned(testCase);
a = lts.prediction.PairedUncertainty.sampleArtifacts(governed, 5, 42);
b = lts.prediction.PairedUncertainty.sampleArtifacts(governed, 5, 42);
verifyEqual(testCase, [a.parameters], [b.parameters]);
verifyEqual(testCase, governed.artifact.parameters(1).value, 130);
end

function testIdentifiabilityFlagsConfoundedColumns(testCase)
x = linspace(0, 1, 20).';
report = lts.validation.IdentifiabilityReport.analyze( ...
    [x, 2*x], ["a", "b"]);
verifyFalse(testCase, report.fullRank);
verifyEqual(testCase, numel(report.confoundedPairs), 1);
end

function testDatasetCatalogStartsProvisional(testCase)
catalog = lts.governance.DatasetCatalog.load(fullfile( ...
    testCase.TestData.root, 'config', 'governance', ...
    'r25_dataset_catalog.json'));
verifyEqual(testCase, ...
    lts.governance.DatasetCatalog.maximumCertification(catalog), ...
    "provisional");
end

function testValidationDatasetCannotLeakIntoCalibration(testCase)
manifest = lts.governance.ParameterManifest.load( ...
    testCase.TestData.manifestFile);
dataset = struct('id', "held_out", 'role', "baseline-validation", ...
    'vehicleConfiguration', "R25", 'testDay', "synthetic", ...
    'sourceFile', "does_not_matter.csv", ...
    'sha256', repmat('0', 1, 64), 'conditions', struct(), ...
    'intervention', struct());
catalog = struct('schema', "lts.governance.dataset-catalog.v1", ...
    'datasets', dataset);
stage = struct('name', "mass_properties", ...
    'parameters', "yaw_inertia", ...
    'residual', @(candidate) candidate.yawInertia - 150);
verifyError(testCase, @() lts.app.calibrate_plant( ...
    'Manifest', manifest, 'DatasetCatalog', catalog, ...
    'DatasetIds', "held_out", 'Stages', stage), ...
    'calibrate_plant:DatasetLeakage');
end

function testCertificationGateRequiresNoRefitAndAccurateDelta(testCase)
catalog = struct('schema', "lts.governance.dataset-catalog.v1", ...
    'datasets', struct('id', "ballast_ab", ...
        'role', "transport-validation", ...
        'vehicleConfiguration', "R25_ballast", 'testDay', "synthetic", ...
        'sourceFile', "ballast.csv", 'sha256', repmat('0', 1, 64), ...
        'conditions', struct(), 'intervention', struct('deltaMassKg', 5)));
baseline = struct('absoluteErrorFraction', 0.01);
transport = struct('measuredDeltaS', 0.5, 'predictedDeltaS', 0.6, ...
    'variantRefitted', false);
result = lts.validation.CertificationGate.assess( ...
    catalog, baseline, transport);
verifyEqual(testCase, result.certification, "transport-validated");
transport.variantRefitted = true;
result = lts.validation.CertificationGate.assess( ...
    catalog, baseline, transport);
verifyEqual(testCase, result.certification, "baseline-validated");
end

function testStagedCalibrationImprovesGovernedParameter(testCase)
manifest = lts.governance.ParameterManifest.load( ...
    testCase.TestData.manifestFile);
config = lts.vehicles.R25();
stage = struct('name', "mass_properties", ...
    'parameters', "yaw_inertia", ...
    'residual', @(candidate) (candidate.yawInertia - 150) / 2);
output = lts.calibration.StagedCalibrator.fit(config, manifest, stage, ...
    'MaxIterations', 80, 'ArtifactId', 'synthetic');
verifyLessThan(testCase, abs(output.config.yawInertia - 150), ...
    abs(config.yawInertia - 150));
verifyEqual(testCase, string(output.artifact.certification), "provisional");
verifyTrue(testCase, output.stages.identifiability.fullRank);
end

function testDesignStudyRunsPairedWithoutRefit(testCase)
governed = localGoverned(testCase);
change = lts.prediction.DesignChange.load(fullfile( ...
    testCase.TestData.root, 'config', 'design_changes', ...
    'example_ballast_removal.json'));
track = lts.components.TestTrack('straight10');
result = lts.prediction.DesignStudy.run(governed, change, track, ...
    'AllowProvisional', true, ...
    'OptimizerOptions', struct('Dt', 0.01, ...
        'LineOffsetFractions', 0.65, 'UsageSchedule', 0.75));
verifyTrue(testCase, isfinite(result.baseline.lapTime));
verifyTrue(testCase, isfinite(result.variant.lapTime));
verifyFalse(testCase, result.variantRefitted);
verifyEqual(testCase, result.decisionStatus, "uncertified");
verifyLessThan(testCase, result.variant.lapTime, result.baseline.lapTime);
repeat = lts.prediction.HierarchicalOptimizer.optimize( ...
    governed.config, track, 'Dt', 0.01, ...
    'LineOffsetFractions', 0.65, 'UsageSchedule', 0.75);
verifyEqual(testCase, repeat.lapTime, result.baseline.lapTime, ...
    'AbsTol', 1e-12);
end

function testCleanR25AndLegacyOverlayAreSeparated(testCase)
clean = lts.vehicles.R25();
legacy = lts.vehicles.R25_correlation_tuning(clean);
verifyEqual(testCase, clean.tire.tirFile, ...
    'Hoosier 43100 18.0x6.0-10 R20_7.tir');
verifyEqual(testCase, legacy.tire.tirFile, ...
    'Hoosier 43100 18.0x6.0-10 R20_7 - Scaled.tir');
verifyEqual(testCase, clean.aero.CdA, 1.81, 'AbsTol', 1e-12);
verifyEqual(testCase, legacy.aero.CdA, 2.65, 'AbsTol', 1e-12);
end

function governed = localGoverned(testCase)
governed = lts.governance.GovernedVehicle.build(@lts.vehicles.R25, ...
    testCase.TestData.manifestFile, testCase.TestData.artifactFile);
end
