classdef SimulatorZeroAero < handle
    methods
        function forces = computeForces(~, ~)
            forces = struct( ...
                'Fz_front', 0, ...
                'Fz_rear', 0, ...
                'F_drag', 0, ...
                'dragHeight', 0);
        end
    end
end
