function tf = tireDataAvailable()
%TIREDATAAVAILABLE True when the TTC tire data files are present locally.
%   The .tir files under data/tires are untracked (FSAE Tire Test
%   Consortium member data; see src/+lts/+components/+Tire/README.md).
%   Tire-dependent tests use this to skip cleanly when the files are
%   absent, e.g. on a fresh clone or CI runner.
repoRoot = fullfile(fileparts(mfilename('fullpath')), '..');
searchFolders = { ...
    fullfile(repoRoot, 'data', 'tires'); ...
    fullfile(repoRoot, 'src', '+lts', '+components', '+Tire')};
required = { ...
    '43105_18x7.5_10_R25B_7.tir', ...
    'Hoosier 43100 18.0x6.0-10 R20_7 - Scaled.tir'};
tf = any(cellfun(@(folder) ...
    all(cellfun(@(name) isfile(fullfile(folder, name)), required)), ...
    searchFolders));
end
