function cfg = R25()
    % R25 FSAE car configuration (GENERATED from the design spec sheet)
    %
    % Auto-generated by scripts/generate_vehicle.py from the FSAE EV
    % Design Spec Sheet CSV. Fields annotated with their provenance:
    %   [CSV rN: ...]            -> direct mapping (value taken from CSV)
    %   TODO derivable (...)     -> derivable but ambiguous; left at default
    %   [not in spec sheet]      -> no CSV source; baseline default kept
    %
    % Units: SI throughout (m, kg, N, s, rad, Pa).

    cfg = lts.vehicle.VehicleConfig();

    cfg.name = "R25";
    %% ====================================================================
    %  VEHICLE-LEVEL CONSTANTS
    %  Mass includes the driver. x forward, y left, z up; CG height from
    %  the ground. Pitch/roll inertia are derived in SimpleChassis from
    %  mass + geometry; only yaw inertia is specified here.
    %  ====================================================================
    cfg.totalMass                    = 264;        %  [CSV r10: 196 kg + 68.0 kg driver] (kg, with driver)
    cfg.wheelbase                    = 1.528;      %  [CSV r8: 1528 mm] [m]
    cfg.trackWidth                   = 1.21;       %  [CSV r8: Front Track 1210 mm] [m]
    cfg.cgHeight                     = 0.256;        %  [CSV r9: 256 (unit column says 'mm' but value is clearly metres; kept as 256 m per baseline/R26)] [m]
    cfg.yawInertia                   = 130;        %  [not in spec sheet -- baseline default 130] [kg*m^2]
    cfg.airDensity                   = 1.225;      % [kg/m^3] (ISA standard; CSV aero r131 was evaluated at rho=1.162)
    cfg.staticFrontWeight            = 0.5095;     %  [CSV r11: 50.95% front] [0-1]
    cfg.brakeBiasFront               = 0.6;        %  TODO derivable: CSV r46: line pressures F 14.524/R 20.836 bar, r44 pistons F4/R2 => front clamp-fraction ~ 0.582 (rough; ignores piston bore 25 vs 25.4 mm). Verify against bias bar. [0-1]
    cfg.brakeForceCoefficient        = 0.7;        %  TODO derivable: CSV r46 is a 'Force @ 1g Deceleration' table; the system is sized for ~1g but brakeForceCoefficient is tyre-limited capacity. baseline 0.70 left as-is.
    brakePressureFrontAt1gBar = 14.524;            %  [CSV r46: front line pressure at 1g deceleration] [bar]
    brakePressureRearAt1gBar = 20.836;             %  [CSV r46: rear line pressure at 1g deceleration] [bar]
    cfg.brakePressure = struct( ...
        'frontForcePerBar', cfg.totalMass * 9.80665 * cfg.brakeBiasFront / brakePressureFrontAt1gBar, ...
        'rearForcePerBar', cfg.totalMass * 9.80665 * (1 - cfg.brakeBiasFront) / brakePressureRearAt1gBar);
    cfg.maxSpeed                     = 80;         %  [not in spec sheet -- baseline default 80] [m/s] (~288 km/h)
    cfg.unsprungMass                 = 9.3;         %  TODO derivable: CSV r47-53 list upright/hub/bearing/axle/brake components as text (no clean per-corner mass). Sum them manually if needed; baseline 25 kg/corner left as-is. [kg/corner]

    %% ====================================================================
    %  AERODYNAMICS
    %  Whole-car aero is represented by one resultant at the center of
    %  pressure. xPosition > 0 is forward of CG, < 0 is behind. zPosition is
    %  kept at CG height so drag adds no artificial pitch moment.
    %  ====================================================================
    % NOTE: the spec sheet (r131-132) gives WHOLE-CAR aero, measured at
    % 80 kph. CSV whole-car totals:
    %   Downforce 1389.9 N  Drag 518.8 N  %Front 47.73
    %   Cl x RefArea(1.094 m^2) => ClA ~ 4.84  CdA ~ 1.81
    %   (downforce independently implies ClA ~ 4.84 -- ~-0% above Cl*Area; CSV is internally inconsistent)
    % xPosition = wheelbase * (%Front - staticFrontWeight).
    cfg.aero = struct( ...
        'xPosition', -0.049202, ...      % [CSV r131: 47.73% front CoP]
        'zPosition', cfg.cgHeight, ...   % Kept at CG height
        'ClA', 4.84, ...                 % [CSV r132: Cl * RefArea]
        'CdA', 1.81, ...                 % [CSV r132: Cd * RefArea]
        'pitchSensitivityClA', 0.0);     % [not in spec sheet]

    %% ====================================================================
    %  SUSPENSION
    %  Per-axle spring/damper. Wheel rate = springRate * motionRatio^2.
    %  ====================================================================

    cfg.suspension.front = struct( ...
        'springRate', 52537.9, ...      %   [CSV r21 shows 5.25 N/mm, but CSV r22 roll rate 671.26 N*m/deg at 1210 mm track implies 52.5 N/mm; using corrected wheel rate] [N/m]
        'dampingCoeff', 13938.1, ...     %   [CSV r24: 400% critical jounce damping at corrected wheel rate and sprung corner mass] [N*s/m]
        'reboundCoeff', 2787.6);         %   [CSV r25: 80% critical rebound damping at corrected wheel rate and sprung corner mass] [N*s/m]

    cfg.suspension.rear = struct( ...
        'springRate', 52537.9, ...      %   [CSV r21 shows 5.25 N/mm, but CSV r22 roll rate 671.26 N*m/deg at 1210 mm track implies 52.5 N/mm; using corrected wheel rate] [N/m]
        'dampingCoeff', 10256.8, ...     %   [CSV r24: 300% critical jounce damping at corrected wheel rate and sprung corner mass] [N*s/m]
        'reboundCoeff', 3077.1);         %   [CSV r25: 90% critical rebound damping at corrected wheel rate and sprung corner mass] [N*s/m]

    cfg.suspension.motionRatio    = 1;     %   [CSV r26]
    cfg.suspension.bumpStopLength = 0.0254;   %   [CSV r20: 25.4 mm jounce travel]
    cfg.suspension.bumpStopRate   = 200000;   % [not in spec sheet] [N/m]
    cfg.suspension.tireSpringRate = 200000;   % [not in spec sheet] [N/m]

    % Suspension geometry: per-axle lookup tables indexed by wheel travel [m].
    cfg.suspension.geometry.front = struct( ...
        'travelGrid',       [-0.0254 0 0.0254], ...
        'camberCurve',      [0.56746 -0.7 -1.96746] * pi / 180, ... %   [CSV r27/r30: -0.7 deg static, -49.9 deg/m bump camber gain]
        'toeCurve',         [0.75 0.75 0.75] * pi / 180, ...        %   [CSV r29: -1.5 deg total front toe-out -> +0.75 deg per wheel in simulator sign convention]
        'motionRatioCurve', [1 1 1], ...                            %   [CSV r26: 1:1 linear motion ratio]
        'rollCenterHeight', 0.034977, ...                     %   [CSV r33: 34.977 mm]
        'casterAngle',      4 * pi / 180, ...                 %   [CSV r35: 4 deg]
        'mechanicalTrail',  0.0143, ...                       %   [CSV r35: 14.3 mm] [m]
        'scrubRadius',      0.02093, ...                      %   [CSV r35: 20.93 mm] [m]
        'kingpinInclination', 10.7 * pi / 180, ...            %   [CSV r36: 10.7 deg]
        'kingpinOffset',    0.05933);                         %   [CSV r36: 59.33 mm] [m]
    cfg.suspension.geometry.rear = struct( ...
        'travelGrid',       [-0.0254 0 0.0254], ...
        'camberCurve',      [1.09672 -0.6 -2.29672] * pi / 180, ... %   [CSV r27/r30: -0.6 deg static, -66.8 deg/m bump camber gain]
        'toeCurve',         [0 0 0] * pi / 180, ...                  %   [CSV r29: 0 deg rear toe]
        'motionRatioCurve', [1 1 1], ...                             %   [CSV r26: 1:1 linear motion ratio]
        'rollCenterHeight', 0.050496, ...                     %   [CSV r33: 50.496 mm]
        'casterAngle',      0, ...
        'mechanicalTrail',  0, ...
        'scrubRadius',      0, ...
        'kingpinInclination', 0, ...
        'kingpinOffset',    0);
    cfg.suspension.geometry.steering = struct( ...
        'steeringRatio',      1, ...
        'ackermann',          1.0207, ...
        'maxWheelSteerAngle', 0.6, ...                      % [not in spec sheet] [rad] (~34 deg)
        'rearSteerRatio',     0.0);

    % Anti-roll bars: no installed ARB rate is specified in the sheet, and
    % CSV r22 roll rate is already matched by the corrected wheel rates.
    cfg.suspension.frontArb = struct( ...
        'stiffness', 0, ...              % [not in spec sheet]
        'motionRatio', 1, ...            % [not in spec sheet]
        'leverArm', 1, ...               % [not in spec sheet] [m]
        'enabled', false);
    cfg.suspension.rearArb = struct( ...
        'stiffness', 0, ...              % [not in spec sheet]
        'motionRatio', 1, ...
        'leverArm', 1, ...
        'enabled', false);

    cfg.suspension.rollStiffnessOverride = NaN;             % [not in spec sheet] derive from springs+ARBs
    cfg.suspension.coupleChassisRollToLoadTransfer = false; % [not in spec sheet]

    %% ====================================================================
    %  CHASSIS (sprung-mass platform heave/pitch/roll)
    %  ====================================================================
    cfg.chassis = struct( ...
        'heaveStiffness', 160000, ...    % [not in spec sheet] [N/m]
        'heaveDamping', 12000, ...       % [not in spec sheet] [N*s/m]
        'pitchStiffness', 90000, ...     % [not in spec sheet] [N*m/rad]
        'pitchDamping', 6000, ...        % [not in spec sheet]
        'rollStiffness', 55000, ...      % [not in spec sheet] fallback only; suspension roll rate derives from springs with ARBs disabled [N*m/rad]
        'rollDamping', 5000, ...         % [not in spec sheet] [N*m*s/rad]
        'torsionalRigidity', 178307, ... %   [CSV r78: 3112.04 N*m/deg (Physical Test) x 180/pi] [N*m/rad]
        'torsionalDamping', 2000);       % [not in spec sheet] [N*m*s/rad]

    %% ====================================================================
    %  POWERTRAIN
    %  Single-speed EV. matFile = '' selects the default motor map;
    %  final drive is fixed in the map. Drivetrain is RWD.
    %    differential.type: 'open' | 'locked' (spool) | 'lsd' | 'drexler'
    %  ====================================================================
    % matFile '' = default EMRAX 228 map (CSV r85 confirms 'Emrax 228')
    cfg.powertrain = struct( ...
        'matFile', '', ...
        'efficiency', 0.85, ...          % [not in spec sheet] [0-1]
        'throttleMapInput', [0.00 0.15 0.35 0.60 0.80 1.00], ...
        'throttleMapOutput', [0.00 0.02 0.10 0.28 0.58 1.00], ...
        'differential', struct(type='drexler', accelRampAngleDeg=30, decelRampAngleDeg=45, fluid="Motul Gear Competition 75W-140", rampTorqueScale = 1, preloadBreakawayTorqueNm = 10));  %   [CSV r122: Drexler M-Diff LSD, non-adjustable preload]

    %% ====================================================================
    %  TIRE
    %  Pacejka Magic Formula (MF 6.1) via MFeval; tirFile lives in +Tire/.
    %  ====================================================================
    % NOTE: CSV r14 lists '16.0x7.5-10 R20 Hoosier'. The default tirFile below is for an
    % 18x7.5-10 Hoosier until a matching 16x7.5-10 .tir is available, but
    % wheelRadius follows the 16.0 in tire diameter from the spec sheet.
    cfg.tire = struct( ...
        'tirFile', '43105_18x7.5_10_R25B_7.tir', ... % [verify vs CSV r14 tire size]
        'wheelInertia', 0.5, ...         % [not in spec sheet] [kg*m^2]
        'relaxationLength', 0.30, ...    % [not in spec sheet] [m]
        'wheelRadius', 0.2032, ...       % [CSV r14: 16.0 in tire diameter / 2]
        'rollingResistanceCoeff', 0.015, ... % [not in spec sheet]
        'bearingDragCoeff', 0);          % [not in spec sheet]
end
