function envelope = lateralEnvelope(tire, loadsN, slipAnglesDeg)
%LATERALENVELOPE Peak lateral force vs normal load.
%   Batched Pacejka sweep over slip angle; peakForce(Fz) = max_alpha |Fy|,
%   with the slip angle that produces it.
Fy = wsc.lateralForceGrid(tire, loadsN, slipAnglesDeg);
[peakForceN, slipIdx] = max(abs(Fy), [], 2);
envelope = struct( ...
    'loadsN', loadsN(:), ...
    'peakForceN', peakForceN(:), ...
    'slipAtPeakDeg', slipAnglesDeg(slipIdx).', ...
    'slipAnglesDeg', slipAnglesDeg, ...
    'lateralForceN', Fy);
end
