function envelope = longitudinalEnvelope(tire, loadsN, slipRatios)
%LONGITUDINALENVELOPE Peak longitudinal force vs normal load.
%   Batched Pacejka sweep over slip ratio (pure longitudinal:
%   alpha = gamma = phit = 0); peakForce(Fz) = max_kappa |Fx|, with the slip
%   ratio that produces it.
Fx = wsc.longitudinalForceGrid(tire, loadsN, slipRatios);
[peakForceN, slipIdx] = max(abs(Fx), [], 2);
envelope = struct( ...
    'loadsN', loadsN(:), ...
    'peakForceN', peakForceN(:), ...
    'kappaAtPeak', slipRatios(slipIdx).', ...
    'slipRatios', slipRatios, ...
    'longitudinalForceN', Fx);
end
