function styleFigure(fig)
%STYLEFIGURE Print-friendly black-on-white defaults for a figure's axes.
set(fig, ...
    'DefaultTextColor', 'k', ...
    'DefaultAxesColor', 'w', ...
    'DefaultAxesXColor', 'k', ...
    'DefaultAxesYColor', 'k', ...
    'DefaultLegendColor', 'w', ...
    'DefaultLegendTextColor', 'k');
end
