classdef CorrelationTuningEvaluator
    %CORRELATIONTUNINGEVALUATOR Evaluate physical candidates on replay windows.

    methods (Static)
        function windows = makeWindows(profile, horizonS)
            horizons = unique(sort(double(horizonS(:).')));
            if isempty(horizons) || any(~isfinite(horizons)) || any(horizons <= 0)
                error('lts_correlation_CorrelationTuningEvaluator:InvalidHorizons', ...
                    'Prediction horizons must be positive finite values.');
            end
            blockLength = max(horizons);
            starts = (0:blockLength:(profile.duration() - blockLength + 1e-12)).';
            anchorCount = numel(starts);
            rowCount = anchorCount * numel(horizons);
            ids = (1:rowCount).';
            anchorIds = repelem((1:anchorCount).', numel(horizons));
            starts = repelem(starts, numel(horizons));
            horizonColumn = repmat(horizons(:), anchorCount, 1);
            split = repmat("train", rowCount, 1);
            split(mod(anchorIds, 2) == 0) = "validation";
            windows = table(ids, anchorIds, starts, horizonColumn, split, ...
                'VariableNames', {'window_id', 'anchor_id', 'start_s', ...
                'horizon_s', 'split'});
        end

        function [profile, report] = prepareProfile(profile, config, varargin)
            parser = inputParser;
            parser.addParameter('PreferGpsKinematics', true, ...
                @(x) islogical(x) || isnumeric(x));
            parser.addParameter('GpsSmoothingS', 0.35, ...
                @(x) isnumeric(x) && isscalar(x) && isfinite(x) && x > 0);
            parser.parse(varargin{:});
            report = struct('regenRepairStatus', "disabled", ...
                'regenRepairSampleCount', 0, ...
                'gpsKinematicsStatus', "disabled", ...
                'gpsKinematicsSampleCount', 0, ...
                'gpsSmoothingS', double(parser.Results.GpsSmoothingS));
            repair = lts.correlation.CorrelationAppSupport.vehicleCorrelationFlag( ...
                config, 'repairInvalidDeliveredRegen', false);
            if repair && profile.hasMotorTorqueDelivered()
                [profile, repairReport] = profile.withPowerConservingRegenRepair( ...
                    'PackPowerAdvanceS', ...
                    lts.correlation.CorrelationAppSupport.vehicleCorrelationScalar( ...
                        config, 'regenRepairPackPowerAdvanceS', -0.015), ...
                    'MinimumChargingPowerW', ...
                    lts.correlation.CorrelationAppSupport.vehicleCorrelationScalar( ...
                        config, 'regenRepairMinimumChargingPowerW', 1000), ...
                    'MinimumMotorSpeedRpm', ...
                    lts.correlation.CorrelationAppSupport.vehicleCorrelationScalar( ...
                        config, 'regenRepairMinimumMotorSpeedRpm', 300), ...
                    'RegenRequestThresholdNm', ...
                    lts.correlation.CorrelationAppSupport.vehicleCorrelationScalar( ...
                        config, 'regenRepairRequestThresholdNm', 5), ...
                    'PowerToleranceW', ...
                    lts.correlation.CorrelationAppSupport.vehicleCorrelationScalar( ...
                        config, 'regenRepairPowerToleranceW', 500), ...
                    'MaximumRegenEfficiency', ...
                    lts.correlation.CorrelationAppSupport.vehicleCorrelationScalar( ...
                        config, 'regenRepairMaximumEfficiency', 1), ...
                    'MaximumReconstructedTorqueNm', ...
                    lts.correlation.CorrelationAppSupport.vehicleCorrelationScalar( ...
                        config, 'regenRepairMaximumTorqueNm', 170));
                report.regenRepairStatus = string(repairReport.status);
                report.regenRepairSampleCount = repairReport.repairedSampleCount;
            end
            profile = profile.withSteeringCalibration( ...
                lts.correlation.CorrelationAppSupport.vehicleCorrelationScalar( ...
                    config, 'steeringCenterGain', 1), ...
                lts.correlation.CorrelationAppSupport.vehicleCorrelationScalar( ...
                    config, 'steeringCalibrationEndAngleRad', deg2rad(22)), ...
                lts.correlation.CorrelationAppSupport.vehicleCorrelationScalar( ...
                    config, 'steeringDelayS', 0), ...
                lts.correlation.CorrelationAppSupport.vehicleCorrelationScalar( ...
                    config, 'steeringCenterOffsetRad', 0));
            if logical(parser.Results.PreferGpsKinematics)
                [profile, gpsReport] = profile.withGpsKinematics( ...
                    'SmoothingWindowS', parser.Results.GpsSmoothingS);
                report.gpsKinematicsStatus = string(gpsReport.status);
                report.gpsKinematicsSampleCount = gpsReport.sampleCount;
            end
        end

        function [summary, detail] = evaluateCandidate(candidateId, values, ...
                registry, baseConfig, profile, track, windows, varargin)
            parser = inputParser;
            parser.addParameter('Dt', 0.001);
            parser.addParameter('ExcludeInitialS', 0.1);
            parser.addParameter('Split', "train");
            parser.addParameter('WheelSolveIterations', 2);
            parser.parse(varargin{:});
            opts = parser.Results;

            selected = windows(string(windows.split) == string(opts.Split), :);
            detail = lts.correlation.CorrelationTuningEvaluator.emptyDetail( ...
                height(selected));
            config = lts.correlation.CorrelationParameterRegistry.apply( ...
                registry, baseConfig, values);
            for i = 1:height(selected)
                window = selected(i, :);
                detail.candidate_id(i) = candidateId;
                detail.window_id(i) = window.window_id;
                detail.start_s(i) = window.start_s;
                detail.horizon_s(i) = window.horizon_s;
                detail.split(i) = string(opts.Split);
                try
                    segment = profile.window(window.start_s, window.horizon_s);
                    result = lts.correlation.CorrelationTuningEvaluator.simulateAndScore( ...
                        segment, config, track, opts);
                catch err
                    result = lts.correlation.CorrelationScore.failedResult( ...
                        string(err.identifier));
                end
                detail.score(i) = result.score;
                detail.status(i) = result.status;
                detail.sample_count(i) = result.sampleCount;
                detail.speed(i) = result.speed;
                detail.yaw_rate(i) = result.yawRate;
                detail.lateral_accel(i) = result.lateralAccel;
                detail.longitudinal_accel(i) = result.longitudinalAccel;
                detail.wheel_speed(i) = result.wheelSpeed;
                detail.gps_trace(i) = result.gpsTrace;
            end

            finiteScore = isfinite(detail.score);
            if any(finiteScore)
                score = mean(detail.score(finiteScore));
            else
                score = Inf;
            end
            summary = table(candidateId, score, nnz(finiteScore), height(detail), ...
                'VariableNames', {'candidate_id', 'score', ...
                'completed_windows', 'total_windows'});
        end

        function result = simulateAndScore(profile, config, track, opts)
            dt = double(opts.Dt);
            % Vehicle assembly is intentionally verbose for interactive runs;
            % suppress its repeated component inventory inside large searches.
            evalc('vehicle = lts.vehicle.VehicleManager.fromConfig(config, track, dt);');
            initialState = lts.correlation.CorrelationStateInitializer.fromReplayProfile( ...
                profile, [], vehicle, ...
                'UseLoggedPosition', false, ...
                'UseLoggedYawRate', true, ...
                'UseLoggedWheelSpeeds', false, ...
                'UseLoggedDrivenWheelCarrierSpeed', true, ...
                'UseLoggedTransientState', true, ...
                'InitialTransientWindowS', ...
                lts.correlation.CorrelationAppSupport.vehicleCorrelationScalar( ...
                    config, 'initialTransientWindowS', 0.3));
            simulator = lts.simulation.Simulator(vehicle, [], dt);
            simulator.telemetryMode = "lean";
            simulator.verbose = false;
            simulator.wheelSolveIterations = opts.WheelSolveIterations;
            warningState = warning;
            warningCleanup = onCleanup(@() warning(warningState)); %#ok<NASGU>
            warning('off', 'all');
            stateLog = simulator.simulateReplay( ...
                initialState, track, profile, ...
                'ReplayDomain', 'time', ...
                'BrakeMode', 'pressure', ...
                'PowertrainMode', 'motor_torque_delivered', ...
                'LimitMotorTorqueByPackPower', false, ...
                'StopOnOffTrack', false, ...
                'StopAtTrackEnd', false, ...
                'StopAtReplayEnd', true, ...
                'ReferenceMode', 'free');
            result = lts.correlation.CorrelationScore.evaluate( ...
                stateLog, profile, ...
                'ExcludeInitialS', opts.ExcludeInitialS, ...
                'FinalDriveRatio', 3.36, ...
                'WheelRadiusM', config.tire.wheelRadius);
            if ~lts.correlation.CorrelationTuningEvaluator.isFiniteStateLog(stateLog)
                result = lts.correlation.CorrelationScore.failedResult( ...
                    "nonfinite_physics_state");
            end
        end

        function tf = isFiniteStateLog(stateLog)
            names = {'speed', 'vx', 'vy', 'yawRate', 'ax', 'ay'};
            tf = true;
            for i = 1:numel(names)
                if ~isfield(stateLog, names{i}) || ...
                        isempty(stateLog.(names{i})) || ...
                        any(~isfinite(stateLog.(names{i})))
                    tf = false;
                    return;
                end
            end
        end
    end

    methods (Static, Access = private)
        function T = emptyDetail(n)
            T = table(zeros(n, 1), zeros(n, 1), zeros(n, 1), zeros(n, 1), ...
                strings(n, 1), inf(n, 1), strings(n, 1), zeros(n, 1), ...
                nan(n, 1), nan(n, 1), nan(n, 1), nan(n, 1), nan(n, 1), nan(n, 1), ...
                'VariableNames', {'candidate_id', 'window_id', 'start_s', ...
                'horizon_s', 'split', 'score', 'status', 'sample_count', 'speed', ...
                'yaw_rate', 'lateral_accel', 'longitudinal_accel', ...
                'wheel_speed', 'gps_trace'});
        end
    end
end
