classDiagram
    direction TB

    class Simulator {
        +vehicleManager
        +driverModel
        +dt
        +step(state, throttle, brake, curKappa, curMu, curHeading)
        +simulate(initialState, track)
    }

    class VehicleManager {
        +aero
        +suspension
        +powertrain
        +tire
        +track
        +totalMass
        +wheelbase
        +trackWidth
        +cgHeight
        +staticFrontWeight
        +maxSpeed
    }

    class DriverModel {
        +vehicleManager
        +lookaheadTime
        +brakingLookahead
        +computeInputs(state)
    }

    class VehicleState {
        +vehicleManager
        +s
        +speed
        +ax
        +ay
        +heading
        +yawRate
        +pitchAngle
        +throttle
        +brake
        +time
        +updateFromDynamics(ax, ay, ds, dt, curvature, heading, mu)
        +toLogStruct()
    }

    class AeroComponent {
        <<abstract>>
        +name
        +xPosition
        +zPosition
        +ClA
        +CdA
        +pitchSensitivityClA
        +computeDownforce(vehicleState)*
        +computeDrag(vehicleState)*
        +computeEffectiveHeight(vehicleState)
    }

    class AeroManager {
        +components
        +addComponent(aeroComp)
        +removeComponent(name)
        +computeForces(vehicleState)
        +computePerComponent(vehicleState)
    }

    class FrontWing {
        +heightSensitivity
        +computeDownforce(vehicleState)
        +computeDrag(vehicleState)
    }

    class RearWing {
        +heightSensitivity
        +computeDownforce(vehicleState)
        +computeDrag(vehicleState)
    }

    class UnderbodyFloor {
        +stallHeight
        +heightExponent
        +computeDownforce(vehicleState)
        +computeDrag(vehicleState)
    }

    class SimpleAero {
        +computeDownforce(vehicleState)
        +computeDrag(vehicleState)
    }

    class SuspensionComponent {
        <<abstract>>
        +computeCornerLoads(state, FzFront, FzRear, totalMass, dt)*
    }

    class SuspensionManager {
        +frontLeft
        +frontRight
        +rearLeft
        +rearRight
        +staticFrontWeight
        +warmup(totalMass, dt)
        +computeCornerLoads(state, FzFront, FzRear, totalMass, dt)
        +computePitchAngle()
    }

    class SimpleSuspension {
        +springRate
        +dampingCoeff
        +reboundCoeff
        +motionRatio
        +bumpStopLength
        +tireSpringRate
        +unsprungMass
        +state
        +updateCorner(cornerState, demandedLoad, dt)
    }

    class SuspensionState {
        +damperPosition
        +damperVelocity
        +tireDeflection
        +tireNormalForce
        +demandedLoad
        +reset()
    }

    class PowertrainComponent {
        <<abstract>>
        +computeDriveForce(speed, throttle)*
        +getMaxTorque(engineSpeed)*
        +getTotalGearRatio()*
        +getDrivetrainEfficiency()*
    }

    class EMRAX228Powertrain {
        +state
        +motorRPMCurve
        +tractiveForceCurveN
        +rpmFalloffStartRPM
        +rpmFalloffFactor
        +rpmLimitRPM
        +computeDriveForce(speed, throttle)
        +updateStateFromDrivenWheels(omega)
        +limitDrivenWheelAngularVelocity(omega)
    }

    class PowertrainState {
        +drivenWheelAngularVelocity
        +drivenWheelRPM
        +motorAngularVelocity
        +motorRPM
        +motorTorque
        +wheelTorque
        +driveForce
        +rpmLimitActive
        +updateFromDrivenWheels(omega, gearRatio)
        +updateOutputs(throttle, motorTorque, wheelTorque, driveForce, efficiency, rpmLimitActive)
        +reset()
    }

    class TireModel {
        <<abstract>>
        +computeLateralForce(normalLoad, slipAngle, mu)*
        +computeLongitudinalForce(normalLoad, slipRatio, mu)*
        +getPeakFriction(normalLoad)*
    }

    class PacejkaTire {
        +tireConstants
        +FL
        +FR
        +RL
        +RR
        +computeSlipRatio(cornerState, vehicleSpeed)
        +updateWheelDynamics(cornerState, driveTorque, brakeTorque, dt)
        +updateAllFromState(state, vehicleManager, cornerLoads, mu)
    }

    class TireState {
        +normalForce
        +slipAngle
        +slipRatio
        +angularVelocity
        +wheelRadius
        +Fx
        +Fy
        +reset()
    }

    class TireConstants {
        +params
        +nomLoad
        +nomPressure
        +refVelocity
    }

    class Track {
        <<abstract>>
        +getTrackPoints()*
        +getCurvature()*
        +getSurfaceFriction()*
        +getTotalLength()*
        +getHeading()*
        +computeCurvature(points)$
        +computeHeading(points)$
    }

    class TestTrack {
        +trackPoints
        +trackCurvature
        +trackHeading
        +trackMu
        +trackLength
        +getTrackPoints()
        +getCurvature()
        +getSurfaceFriction()
        +getTotalLength()
    }

    class GraphPlotter {
        +plotAll(stateLog, lapTime, track, vehicle, aero)$
        +plotAero(stateLog, vehicle, aero)$
        +plotSuspension(stateLog, vehicle)$
        +plotTire(stateLog, vehicle)$
        +plotPowertrain(stateLog, vehicle)$
    }

    AeroComponent <|-- AeroManager
    AeroComponent <|-- FrontWing
    AeroComponent <|-- RearWing
    AeroComponent <|-- UnderbodyFloor
    AeroComponent <|-- SimpleAero

    SuspensionComponent <|-- SuspensionManager
    PowertrainComponent <|-- EMRAX228Powertrain
    TireModel <|-- PacejkaTire
    Track <|-- TestTrack

    Simulator *-- VehicleManager : vehicleManager
    Simulator *-- DriverModel : driverModel
    VehicleManager *-- AeroManager : aero
    VehicleManager *-- SuspensionManager : suspension
    VehicleManager *-- PowertrainComponent : powertrain
    VehicleManager *-- TireModel : tire
    VehicleManager *-- Track : track
    VehicleState --> VehicleManager : vehicleManager

    AeroManager o-- AeroComponent : components
    SuspensionManager *-- SimpleSuspension : corners
    SimpleSuspension *-- SuspensionState : state
    EMRAX228Powertrain *-- PowertrainState : state
    PacejkaTire *-- TireState : corners
    PacejkaTire *-- TireConstants : tireConstants
