classdef DesignStudy
    %DESIGNSTUDY Paired baseline/variant minimum-lap-time prediction.

    methods (Static)
        function result = run(governed, change, track, varargin)
            parser = inputParser;
            parser.addParameter('SampleCount', 0, ...
                @(x) isnumeric(x) && isscalar(x) && x >= 0);
            parser.addParameter('Seed', 25, @(x) isnumeric(x) && isscalar(x));
            parser.addParameter('AllowProvisional', false, ...
                @(x) islogical(x) || isnumeric(x));
            parser.addParameter('OptimizerOptions', struct(), @isstruct);
            parser.parse(varargin{:});
            opts = parser.Results;

            lts.governance.CalibrationArtifact.assertProductionSafe(governed.artifact);
            if string(governed.certification) == "provisional" && ...
                    ~logical(opts.AllowProvisional)
                error('lts_prediction_DesignStudy:ProvisionalRequiresOptIn', ...
                    ['The calibration is provisional. Pass AllowProvisional=true ' ...
                    'for an explicitly uncertified engineering study.']);
            end
            variant = lts.prediction.DesignChange.apply(governed, change);
            baselineResult = lts.prediction.DesignStudy.optimize( ...
                governed.config, track, opts.OptimizerOptions);
            variantResult = lts.prediction.DesignStudy.optimize( ...
                variant.config, track, opts.OptimizerOptions);

            artifacts = lts.prediction.PairedUncertainty.sampleArtifacts( ...
                governed, opts.SampleCount, opts.Seed);
            sampleBase = nan(numel(artifacts), 1);
            sampleVariant = nan(numel(artifacts), 1);
            for i = 1:numel(artifacts)
                baseSample = governed;
                baseSample.artifact = artifacts(i);
                baseSample.config = lts.governance.CalibrationArtifact.apply( ...
                    governed.config, governed.manifest, artifacts(i));
                variantSample = lts.prediction.DesignChange.apply(baseSample, change);
                b = lts.prediction.DesignStudy.optimize( ...
                    baseSample.config, track, opts.OptimizerOptions);
                v = lts.prediction.DesignStudy.optimize( ...
                    variantSample.config, track, opts.OptimizerOptions);
                sampleBase(i) = b.lapTime;
                sampleVariant(i) = v.lapTime;
            end
            deltas = sampleVariant - sampleBase;
            certification = string(governed.certification);
            decisionStatus = "uncertified";
            if certification == "transport-validated"
                decisionStatus = "transport-validated";
            end
            result = struct('schema', "lts.prediction.design-study-result.v1", ...
                'baseline', baselineResult, 'variant', variantResult, ...
                'deltaLapTime', variantResult.lapTime - baselineResult.lapTime, ...
                'sectorDelta', variantResult.sectorTimes - baselineResult.sectorTimes, ...
                'uncertainty', struct( ...
                    'baseline', lts.prediction.PairedUncertainty.summarize(sampleBase), ...
                    'variant', lts.prediction.PairedUncertainty.summarize(sampleVariant), ...
                    'delta', lts.prediction.PairedUncertainty.summarize(deltas), ...
                    'paired', true, 'seed', opts.Seed), ...
                'sensitivityAttribution', ...
                    lts.prediction.DesignStudy.attribute( ...
                        governed, change, track, baselineResult, ...
                        variantResult, opts.OptimizerOptions), ...
                'domainWarnings', unique([governed.domainWarnings; variant.domainWarnings]), ...
                'calibrationId', governed.calibrationId, ...
                'certification', certification, ...
                'decisionStatus', decisionStatus, 'variantRefitted', false);
        end
    end

    methods (Static, Access = private)
        function result = optimize(config, track, options)
            args = {};
            names = fieldnames(options);
            for i = 1:numel(names)
                args(end + 1:end + 2) = {names{i}, options.(names{i})}; %#ok<AGROW>
            end
            result = lts.prediction.HierarchicalOptimizer.optimize(config, track, args{:});
        end

        function attribution = attribute( ...
                baseline, change, track, baselineResult, fullVariantResult, options)
            ops = change.operations;
            effects = repmat(struct('operation', "", 'parameter', "", ...
                'baselineValue', NaN, 'variantValue', NaN, 'units', "", ...
                'isolatedDeltaLapTimeS', NaN), numel(ops), 1);
            for i = 1:numel(ops)
                type = string(ops(i).type);
                effects(i).operation = type;
                if type == "mass"
                    path = "totalMass";
                elseif type == "aero_map"
                    path = "aero.ClA";
                else
                    path = string(ops(i).path);
                end
                p = lts.governance.ParameterManifest.find(baseline.manifest, path);
                singleChange = change;
                singleChange.id = sprintf('%s_operation_%d', char(change.id), i);
                singleChange.operations = ops(i);
                singleVariant = lts.prediction.DesignChange.apply( ...
                    baseline, singleChange);
                if numel(ops) == 1
                    isolated = fullVariantResult;
                else
                    isolated = lts.prediction.DesignStudy.optimize( ...
                        singleVariant.config, track, options);
                end
                effects(i).parameter = path;
                effects(i).baselineValue = ...
                    lts.governance.ParameterManifest.getValue(baseline.config, path);
                effects(i).variantValue = ...
                    lts.governance.ParameterManifest.getValue( ...
                        singleVariant.config, path);
                effects(i).units = string(p.units);
                effects(i).isolatedDeltaLapTimeS = ...
                    isolated.lapTime - baselineResult.lapTime;
            end
            attribution = struct('effects', effects, ...
                'interactionResidualS', ...
                    (fullVariantResult.lapTime - baselineResult.lapTime) - ...
                    sum([effects.isolatedDeltaLapTimeS]));
        end
    end
end
