classdef VehicleConfig
    % VEHICLECONFIG Per-vehicle physics configuration
    %
    % A plain value object that collects every tunable vehicle-physics
    % parameter in one place. One VehicleConfig == one car. Car definitions
    % live in the +vehicles package (e.g. vehicles.baseline) and return a
    % fully-populated VehicleConfig; VehicleManager.fromConfig turns that
    % config into a wired, ready-to-simulate VehicleManager.
    %
    % Sub-systems are nested structs so a car file can override a single
    % field (e.g. cfg.frontWing.ClA = 2.0) without re-declaring the rest.
    % The constructor pre-populates every field with the baseline values, so
    % a car file only needs to spell out the values it wants to change — but
    % vehicles.baseline spells them all out as documentation/template.
    %
    % Scope: vehicle PHYSICS only. Track selection, driver tuning, and the
    % simulation timestep stay in run_simulation.m (they are scenario/test
    % settings, not car properties).

    properties
        % ----------------------------------------------------------------
        % Vehicle-level constants
        % ----------------------------------------------------------------
        totalMass     = 256      % Total mass with driver [kg]
        wheelbase     = 1.558    % Wheelbase [m]
        trackWidth    = 1.21     % Track width [m]
        cgHeight      = 0.3      % CG height [m]
        yawInertia    = 130      % Yaw inertia about CG [kg*m^2]
        airDensity    = 1.225    % Air density [kg/m^3]
        staticFrontWeight    = 0.50 % Static front weight distribution [0-1]
        brakeBiasFront       = 0.60 % Brake force fraction to front axle [0-1]
        brakeForceCoefficient = 0.70 % Brake capacity as fraction of normal load
        maxSpeed      = 80       % Speed limiter [m/s] (~288 km/h)
        unsprungMass  = 25       % Per-corner unsprung mass [kg]

        % ----------------------------------------------------------------
        % Sub-systems (nested structs, initialized in the constructor)
        % ----------------------------------------------------------------
        frontWing     % Front wing aero map
        rearWing      % Rear wing aero map
        underbody     % Underbody floor / diffuser aero map

        suspension    % Springs, damping, ARBs, geometry preset
        chassis       % Heave/pitch/roll platform stiffness & damping

        powertrain    % Motor map, efficiency, differential
        tire          % Tire data file + wheel dynamics
    end

    methods
        function obj = VehicleConfig()
            % VEHICLECONFIG Construct with baseline defaults.
            %   Every sub-system struct is pre-populated so individual
            %   fields can be overridden later (cfg.frontWing.ClA = 2.0).

            % --- Aero: front wing ---
            %   xPosition [m forward of CG], zPosition [m above ground],
            %   ClA, CdA [m^2], pitchSensitivityClA [1/rad],
            %   heightSensitivity [fractional ClA change per cm]
            obj.frontWing = struct( ...
                'xPosition', 0.9, ...
                'zPosition', 0.08, ...
                'ClA', 1.6, ...
                'CdA', 0.35, ...
                'pitchSensitivityClA', -5.0, ...
                'heightSensitivity', 0.3);

            % --- Aero: rear wing ---
            obj.rearWing = struct( ...
                'xPosition', -0.85, ...
                'zPosition', 0.45, ...
                'ClA', 2.1, ...
                'CdA', 1.15, ...
                'pitchSensitivityClA', 3.0, ...
                'heightSensitivity', 0.15);

            % --- Aero: underbody floor / diffuser ---
            %   stallHeight [m], heightExponent [ground-effect curve]
            obj.underbody = struct( ...
                'xPosition', 0.0, ...
                'zPosition', 0.035, ...
                'ClA', 0.4, ...
                'CdA', 0.10, ...
                'pitchSensitivityClA', -8.0, ...
                'stallHeight', 0.015, ...
                'heightExponent', 0.6);

            % --- Suspension ---
            %   front/rear: springRate [N/m], dampingCoeff [N*s/m] (compression),
            %               reboundCoeff [N*s/m]
            %   motionRatio, bumpStopLength [m], bumpStopRate [N/m],
            %   tireSpringRate [N/m]
            %   geometry: suspension/steering kinematics (per-axle curves +
            %             steering model), see the geometry block below
            %   frontArb/rearArb: stiffness [N/m at bar end], motionRatio,
            %                     leverArm [m], enabled
            %   rollStiffnessOverride: NaN = derive from springs+ARBs, else [0-1]
            %   coupleChassisRollToLoadTransfer: opt-in twist coupling
            obj.suspension = struct( ...
                'front', struct('springRate', 45000, 'dampingCoeff', 3000, 'reboundCoeff', 4500), ...
                'rear',  struct('springRate', 42000, 'dampingCoeff', 2800, 'reboundCoeff', 4200), ...
                'motionRatio', 0.95, ...
                'bumpStopLength', 0.025, ...
                'bumpStopRate', 200000, ...
                'tireSpringRate', 200000, ...
                'frontArb', struct('stiffness', 1800, 'motionRatio', 0.95, 'leverArm', 0.26, 'enabled', true), ...
                'rearArb',  struct('stiffness', 1100, 'motionRatio', 0.95, 'leverArm', 0.26, 'enabled', true), ...
                'rollStiffnessOverride', NaN, ...
                'coupleChassisRollToLoadTransfer', false);

            % --- Suspension geometry (kinematics) ---
            %   Per-axle tables indexed by wheel travel [m] (bump = positive):
            %     travelGrid [m], camberCurve [rad] (positive = top-out),
            %     toeCurve [rad] (positive = toe-left),
            %     motionRatioCurve [-], rollCenterHeight [m].
            %   Steering model: steerInput is treated as road-wheel angle.
            %     ackermann: 0 = parallel steer, 1 = ideal Ackermann.
            %   (Vehicle-level wheelbase/track/weight are pulled from the
            %    VehicleManager at construction, not duplicated here.)
            obj.suspension.geometry = struct( ...
                'front', struct( ...
                    'travelGrid',       [-0.05 0 0.05], ...
                    'camberCurve',      [0.5 0 -1.5] * pi / 180, ...
                    'toeCurve',         [-0.05 0 0.05] * pi / 180, ...
                    'motionRatioCurve', [0.93 0.95 0.97], ...
                    'rollCenterHeight', 0.030), ...
                'rear', struct( ...
                    'travelGrid',       [-0.05 0 0.05], ...
                    'camberCurve',      [0.25 0 -0.8] * pi / 180, ...
                    'toeCurve',         [0.05 0 -0.05] * pi / 180, ...
                    'motionRatioCurve', [0.94 0.95 0.96], ...
                    'rollCenterHeight', 0.045), ...
                'steering', struct( ...
                    'steeringRatio',      1.0, ...
                    'ackermann',          0.8872, ...
                    'maxWheelSteerAngle', 0.6, ...
                    'rearSteerRatio',     0.0));

            % --- Chassis (sprung-mass platform heave/pitch/roll) ---
            %   Stiffness [N/m or N*m/rad], damping [N*s/m or N*m*s/rad].
            %   Pitch/roll inertia are derived from mass + geometry in
            %   SimpleChassis, so they are not part of the config.
            obj.chassis = struct( ...
                'heaveStiffness', 160000, ...
                'heaveDamping', 12000, ...
                'pitchStiffness', 90000, ...
                'pitchDamping', 6000, ...
                'rollStiffness', 55000, ...
                'rollDamping', 5000, ...
                'torsionalRigidity', 229183, ...
                'torsionalDamping', 2000);

            % --- Powertrain ---
            %   matFile: '' uses the default EMRAX 228 map in +Powertrain/
            %   efficiency: drivetrain efficiency [0-1]
            %   differential: struct with 'type' in {'open','locked','lsd'};
            %     'lsd' may carry preload/ramp/speedGain/biasRatio
            obj.powertrain = struct( ...
                'matFile', '', ...
                'efficiency', 0.92, ...
                'differential', struct('type', 'open'));

            % --- Tire ---
            %   tirFile: Pacejka .tir filename in +Tire/
            %   wheelInertia [kg*m^2], relaxationLength [m],
            %   wheelRadius [m] (effective rolling radius)
            obj.tire = struct( ...
                'tirFile', '43105_18x7.5_10_R25B_7.tir', ...
                'wheelInertia', 0.5, ...
                'relaxationLength', 0.30, ...
                'wheelRadius', 0.241935);
        end
    end
end
