%% verify_pacejka_invariants.m
% Focused checks for the Pacejka/MFeval tire wrapper.
%
% This script depends on the MFeval toolbox and the bundled .tir file. It is
% separate from verify_physics_invariants.m so the lightweight physics suite
% can still run without external tire-toolbox dependencies.

clear; clc;

tire = components.Tire.PacejkaTire('43105_18x7.5_10_R25B_7.tir');

arbitraryLoads = [123.4, 687.3, 999.1, 1042.7, 1379.4, 2468.8];
for i = 1:numel(arbitraryLoads)
    Fz = arbitraryLoads(i);
    Fx = tire.computeLongitudinalForce(Fz, 0, 1.2);
    Fy = tire.computeLateralForce(Fz, 0, 1.2);
    assertClose(Fx, 0, 1e-10, ...
        sprintf('standalone zero-slip Fx at Fz %.1f', Fz));
    assertClose(Fy, 0, 1e-10, ...
        sprintf('standalone zero-slip Fy at Fz %.1f', Fz));

    tire.updateCorner(tire.FL, Fz, 0, 0, 0, 1.2);
    assertClose(tire.FL.Fx, 0, 1e-10, ...
        sprintf('corner zero-slip Fx at Fz %.1f', Fz));
    assertClose(tire.FL.Fy, 0, 1e-10, ...
        sprintf('corner zero-slip Fy at Fz %.1f', Fz));
    assertClose(tire.FL.Mz, 0, 1e-10, ...
        sprintf('corner zero-slip Mz at Fz %.1f', Fz));
end

testLoad = 1042.7;
tire.updateCorner(tire.FL, testLoad, 0, 0.10, 0, 1.2);
assert(tire.FL.Fx > 0, 'Pure longitudinal slip should create Fx.');
assertClose(tire.FL.Fy, 0, 1e-10, ...
    'Pure longitudinal slip should not create Fy.');
assertClose(tire.FL.Mz, 0, 1e-10, ...
    'Pure longitudinal slip should not create Mz.');

tire.updateCorner(tire.FL, testLoad, 0.08, 0, 0, 1.2);
assertClose(tire.FL.Fx, 0, 1e-10, ...
    'Pure lateral slip should not create Fx.');
assert(tire.FL.Fy > 0, 'Pure positive lateral slip should create positive Fy.');
assert(abs(tire.FL.Mz) > 0, 'Pure lateral slip should create aligning moment.');

tire.updateCorner(tire.FL, testLoad, 0.08, 0.10, 0, 1.2);
assert(tire.FL.Fx > 0 && tire.FL.Fy > 0, ...
    'Combined slip should preserve nonzero Fx and Fy.');
assert(tire.FL.frictionUsage <= 1 + 1e-10, ...
    'Combined slip should respect the friction ellipse.');

vectorNormalFy = tire.computeLateralForce([1000, 1100], 0.05, 1.2);
vectorSlipFx = tire.computeLongitudinalForce(1000, [0.05, 0.10], 1.2);
stringSpeedKappa = tire.computeSlipRatio(tire.FL, string('bad'));
malformedWheelTelemetry = tire.updateWheelDynamics( ...
    tire.FL, [1, 2], string('bad'), string('bad'));
malformedWheelKinematics = tire.computeWheelKinematics( ...
    [10, 20], string('bad'), [0, 1], [0.1, 0.2], ...
    [1.55, 1.60], [0.45, 0.50], [1.2, 1.3]);
malformedTireVehicle = VehicleManager(components.Aero.AeroManager(), [], ...
    components.Powertrain.SimplePowertrain(), tire, []);
tire.updateAllFromState( ...
    VehicleState('speed', [10, 20], 'vy', string('bad')), ...
    malformedTireVehicle, ...
    struct('FL', [1000, 1001], 'FR', string('bad'), ...
    'RL', 1000, 'RR', 1000), ...
    string('bad'), string('bad'));
assert(isscalar(vectorNormalFy) && isfinite(vectorNormalFy) ...
        && isscalar(vectorSlipFx) && isfinite(vectorSlipFx) ...
        && isscalar(stringSpeedKappa) && isfinite(stringSpeedKappa) ...
        && isscalar(malformedWheelTelemetry.omegaMean) ...
        && isfinite(malformedWheelTelemetry.omegaMean) ...
        && isscalar(malformedWheelKinematics.FL.slipAngle) ...
        && isfinite(malformedWheelKinematics.FL.slipAngle) ...
        && isscalar(tire.FL.Fx) && isfinite(tire.FL.Fx), ...
    'PacejkaTire malformed public inputs should stay scalar finite.');

fprintf('Pacejka invariant checks passed.\n');

function assertClose(actual, expected, tol, label)
    err = abs(actual - expected);
    assert(err <= tol, '%s: expected %.12g, got %.12g (err %.3g)', ...
        label, expected, actual, err);
end
